//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01_Framework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfirmationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfirmationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_01_Framework.Resources.ConfirmationMessages", typeof(ConfirmationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account Has Been Created.
        /// </summary>
        public static string ConfirmRegister {
            get {
                return ResourceManager.GetString("ConfirmRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been successfully created. Now you can log in to your account and complete your account information to everyone Access the facilities and services and   related services.
        /// </summary>
        public static string ConfirmRegisterText {
            get {
                return ResourceManager.GetString("ConfirmRegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password Confirmed Redirecting....
        /// </summary>
        public static string ConfirmResetPassword {
            get {
                return ResourceManager.GetString("ConfirmResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has created successfully..
        /// </summary>
        public static string ConfirmUserCreation {
            get {
                return ResourceManager.GetString("ConfirmUserCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want delete this group?.
        /// </summary>
        public static string DeleteGroupConfirmation {
            get {
                return ResourceManager.GetString("DeleteGroupConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want delete this product?.
        /// </summary>
        public static string DeleteProductConfirmation {
            get {
                return ResourceManager.GetString("DeleteProductConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want delete this role?.
        /// </summary>
        public static string DeleteRoleConfirmation {
            get {
                return ResourceManager.GetString("DeleteRoleConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want delete user?.
        /// </summary>
        public static string DeleteUserConfirmationS1 {
            get {
                return ResourceManager.GetString("DeleteUserConfirmationS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string DeleteUserConfirmationS2 {
            get {
                return ResourceManager.GetString("DeleteUserConfirmationS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordChangedSuccessfully.
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction was completed successfully.
        /// </summary>
        public static string PaymentSuccessMessage {
            get {
                return ResourceManager.GetString("PaymentSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction was completed successfully.
        /// </summary>
        public static string PaymentSuccessMessage1 {
            get {
                return ResourceManager.GetString("PaymentSuccessMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password Email Sent Successfully.
        /// </summary>
        public static string ResetPasswordEmailSent {
            get {
                return ResourceManager.GetString("ResetPasswordEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to return user?.
        /// </summary>
        public static string ReturnUserConfirmationS1 {
            get {
                return ResourceManager.GetString("ReturnUserConfirmationS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ReturnUserConfirmationS2 {
            get {
                return ResourceManager.GetString("ReturnUserConfirmationS2", resourceCulture);
            }
        }
    }
}
