//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01_Framework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_01_Framework.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reactivate your account through the site.
        /// </summary>
        public static string ActivationErrorText {
            get {
                return ResourceManager.GetString("ActivationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation operation failed!.
        /// </summary>
        public static string ActivationErrorTitle {
            get {
                return ResourceManager.GetString("ActivationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Group Have Some Products And Its Impossible To Delete.
        /// </summary>
        public static string DeleteGroupErrorMessage {
            get {
                return ResourceManager.GetString("DeleteGroupErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some users that have this role so its impossible to delete.
        /// </summary>
        public static string DeleteRoleErrorMessage {
            get {
                return ResourceManager.GetString("DeleteRoleErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email Exists currently..
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Current Password Correctly.
        /// </summary>
        public static string EnterCurrentPasswordCorrectly {
            get {
                return ResourceManager.GetString("EnterCurrentPasswordCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Date Correctly.
        /// </summary>
        public static string EnterDateCorrectly {
            get {
                return ResourceManager.GetString("EnterDateCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter at least one of email or phone number.
        /// </summary>
        public static string EnterEmailOrPhoneNumber {
            get {
                return ResourceManager.GetString("EnterEmailOrPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email Or Phone Number Correctly.
        /// </summary>
        public static string EnterEmailOrPhoneNumberCorrectly {
            get {
                return ResourceManager.GetString("EnterEmailOrPhoneNumberCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter other email instead of your current email.
        /// </summary>
        public static string EnterOtherEmail {
            get {
                return ResourceManager.GetString("EnterOtherEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password Correctly.
        /// </summary>
        public static string EnterPasswordCorrectly {
            get {
                return ResourceManager.GetString("EnterPasswordCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password Repeat Correctly.
        /// </summary>
        public static string EnterPasswordRepeatCorrectly {
            get {
                return ResourceManager.GetString("EnterPasswordRepeatCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the phone number correctly.
        /// </summary>
        public static string EnterPhoneNumberCorrectly {
            get {
                return ResourceManager.GetString("EnterPhoneNumberCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there is no such page on the site or this page has been deleted..
        /// </summary>
        public static string Error404Text {
            get {
                return ResourceManager.GetString("Error404Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is inactive. Please check your email or sign in with your phone number.
        /// </summary>
        public static string NoActiveUserAccount {
            get {
                return ResourceManager.GetString("NoActiveUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create a product group first.
        /// </summary>
        public static string NoProductGroupFound {
            get {
                return ResourceManager.GetString("NoProductGroupFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no user with the entered email.
        /// </summary>
        public static string NoUserWithEnteredEmail {
            get {
                return ResourceManager.GetString("NoUserWithEnteredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no user with the entered phone number.
        /// </summary>
        public static string NoUserWithEnteredPhoneNumber {
            get {
                return ResourceManager.GetString("NoUserWithEnteredPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction failed.
        /// </summary>
        public static string PaymentFailed {
            get {
                return ResourceManager.GetString("PaymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This input is Required.
        /// </summary>
        public static string RequiredInput {
            get {
                return ResourceManager.GetString("RequiredInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password Failed.
        /// </summary>
        public static string ResetPasswordFailed {
            get {
                return ResourceManager.GetString("ResetPasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some errors eccured while sending message.
        /// </summary>
        public static string SomeErrorsEccuredWhileSendingMessage {
            get {
                return ResourceManager.GetString("SomeErrorsEccuredWhileSendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code isnt correct.
        /// </summary>
        public static string VerificationCodeIsntCorrect {
            get {
                return ResourceManager.GetString("VerificationCodeIsntCorrect", resourceCulture);
            }
        }
    }
}
